services:
  taitan:
    container_name: taitan
    image: ghcr.io/datasektionen/taitan
    environment:
      - PORT=5000
      - CONTENT_DIR=/content
      - DARKMODE_URL=false
    volumes:
      - ./:/content
    command: ./taitan -v -w
    ports:
      - 5000:5000
  bawang:
    container_name: bawang
    image: ghcr.io/datasektionen/bawang-dev
    environment:
      - TAITAN_URL=http://taitan:5000
      - TAITAN_CACHE_TTL=0
      - PORT=8000
    ports:
      - 8000:8000
