version: '3.8'

services:
  taitan:
    image: ghcr.io/datasektionen/taitan
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CONTENT_DIR=/content

    volumes:
      - ./:/content

  bawang:
    image: ghcr.io/datasektionen/bawang
    ports:
      - "8000:8000"
    environment:
      - TAITAN_URL=http://localhost:5000
      - RAZZLE_TAITAN_URL=http://localhost:5000
      - PORT=8000
    

# volumes:
#   bawang-content: .