services:
  taitan:
    container_name: taitan
    image: ghcr.io/datasektionen/taitan
    environment:
      - PORT=5000
      - CONTENT_DIR=/content
      - DARKMODE_URL=false
    volumes:
      - ./:/content
    command: ./taitan -v -w
    network_mode: host

  bawang:
    container_name: bawang
    image: ghcr.io/datasektionen/bawang
    environment:
      - TAITAN_URL=http://localhost:5000
      - TAITAN_CACHE_TTL=0
      - PORT=8000
    network_mode: host
