services:
  taitan:
    container_name: taitan
    build: ../taitan
    #image: ghcr.io/datasektionen/taitan
    environment:
      - PORT=5000
      - CONTENT_DIR=/content
      - DARKMODE_URL=false
      - DEFAULT_LANG=sv
    volumes:
      - ./:/content
    command: ./taitan -v -w
    ports:
      - 5000:5000

  bawang:
    container_name: bawang
    build: 
      context: ../bawang
      args: 
        RAZZLE_TAITAN_URL: http://localhost:5000
    #image: ghcr.io/datasektionen/bawang-dev
    environment:
      - TAITAN_URL=http://taitan:5000
      - TAITAN_CACHE_TTL=0
      - PORT=8000
    ports:
      - 8000:8000
