version: '3.8'

services:
  taitan:
    image: ghcr.io/datasektionen/taitan
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CONTENT_DIR=/content
    volumes:
      - ./:/content

  bawang:
    build:
      context: https://github.com/datasektionen/bawang.git
      args:
        - RAZZLE_TAITAN_URL=http://localhost:5000
    ports:
      - "8000:8000"
    environment:
      - TAITAN_URL=https://localhost:5000
      # - TAITAN_URL=https://taitan.datasektionen.se
      - TAITAN_CACHE_TTL=0
      - PORT=8000